# Generated by Django 6.0.2 on 2026-04-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='other_work',
            field=models.TextField(help_text='Enter the other works what employee done.please mention all the other works done by the employee.', null=True),
        ),
    ]
