# Generated by Django 6.0.2 on 2026-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprogress',
            name='daily_sets',
            field=models.JSONField(default=dict),
        ),
    ]
